const questionPool = {
  cafe:["쉬는 날에는 보통 뭐 하면서 보내세요?","요즘 제일 자주 듣는 음악이나 보는 콘텐츠 있어요?","여행 가면 계획 세우는 편이에요, 즉흥적인 편이에요?","일 얘기 말고 요즘 가장 재밌는 게 뭐예요?"],
  bar:["분위기 좋은 곳 자주 찾아다니세요?","술은 분위기로 마시는 편이에요, 맛으로 마시는 편이에요?","친구들이 본인을 어떤 사람이라고 많이 말해요?","사람 볼 때 은근히 중요하게 보는 게 있어요?"],
  restaurant:["맛집 찾아다니는 거 좋아하세요?","매운 거 잘 드세요?","먹는 것 말고 요즘 빠져 있는 취미 있어요?","휴가 생기면 국내랑 해외 중 어디가 더 끌려요?"],
  walk:["걷는 거 좋아하세요?","혼자 있는 시간도 좋아하는 편이에요?","요즘 기분 좋아지는 작은 일이 있다면 뭐예요?","주말 하루가 완전히 비면 어떻게 보내고 싶어요?"],
  brunch:["주말 아침에 일찍 움직이는 편이에요?","브런치 같은 느긋한 일정 좋아하세요?","요즘 주말에 가장 하고 싶은 게 뭐예요?","여행 가면 아침형이에요, 늦잠형이에요?"],
  museum:["전시나 공연 자주 보세요?","작품 볼 때 설명을 먼저 읽는 편이에요?","취향이 다른 사람과 같이 보는 것도 재밌지 않아요?","최근에 기억에 남는 콘텐츠 있어요?"]
};
function prefix(persona,state){if(state==="cold")return persona==="direct"?"음... ":"아, 그렇구나. ";if(state==="cool")return"그렇구나. ";if(state==="spark")return persona==="playful"?"ㅋㅋ 그거 좋다. ":"오, 그 얘기 재밌네요. ";return persona==="warm"?"오, 좋네요 :) ":persona==="playful"?"ㅋㅋ ":"";}
export function fallbackReply({persona,place,difficulty,messages,chemistryState="neutral",activeEvent=null}){const users=messages.filter(m=>m.role==="user"),last=users.at(-1)?.content||"",pool=questionPool[place]||questionPool.cafe,p=prefix(persona,chemistryState),idx=Math.min(Math.max(users.length-1,0),pool.length-1);if(activeEvent){const e={silence:"잠깐 조용해졌네요 ㅎㅎ 이런 순간 좀 어색하죠. 요즘 제일 기다리는 일이 있어요?",ex:"아, 예전 연애 얘기가 나와버렸네요. 너무 깊게는 말 안 해도 돼요. 저는 지금 서로 어떤 사람인지 알아가는 게 더 궁금해요.",bill:"슬슬 계산할까요? 저는 각자 편하게 하는 것도 좋고, 다음에 커피 사주는 방식도 좋더라고요.",second:"저 다음 주말은 아직 좀 비어 있어요. 오늘 얘기한 거 중에 같이 해보면 재밌을 것도 있네요.",compliment:"그렇게 말해주니까 기분 좋네요. 고마워요 :) 저는 대화할 때 편하게 웃는 사람이 좋더라고요.",quiet:"제가 갑자기 말이 좀 줄었죠? 피곤한 건 아니고 잠깐 생각했어요. 너무 부담 갖진 마세요."};if(e[activeEvent.id])return e[activeEvent.id];return`${p}${activeEvent.title} 같은 상황도 생기네요. 저는 크게 신경 쓰이진 않아요. ${pool[idx]}`;}if(chemistryState==="cold")return`${p}${users.length>=7?"저는 오늘은 여기까지가 좋을 것 같아요.":"혹시 다른 얘기 해볼까요?"}`;if(chemistryState==="cool"&&users.length%2===0)return`${p}${pool[idx]}`;if(chemistryState==="spark"&&users.length>=6)return`${p}이런 얘기 잘 통하네요. 다음에 비슷한 데 같이 가도 재밌겠어요. ${pool[idx]}`;if(difficulty==="hard"&&users.length%3===0)return persona==="direct"?"음, 그건 조금 의외네요. 본인은 소개팅 상대에게 가장 중요하게 보는 게 뭐예요?":`아 그렇구나. ${pool[idx]}`;if(last.includes("?"))return`${p}저는 새로운 걸 해보는 편이에요. 너무 빡빡한 계획은 싫고요. ${pool[idx]}`;return`${p}${pool[idx]}`;}
export function fallbackEvaluation(messages){const users=messages.filter(m=>m.role==="user").map(m=>m.content),total=users.reduce((a,b)=>a+b.length,0),questions=users.filter(t=>/\?|어때|세요|나요|뭐|어디|언제|왜/.test(t)).length,empathy=users.filter(t=>/그렇|맞아|좋|이해|재밌|궁금|ㅋㅋ|ㅎㅎ/.test(t)).length,warmth=users.filter(t=>/좋|반가|재밌|궁금|다음|또|ㅋㅋ|ㅎㅎ/.test(t)).length,balanced=users.filter(t=>t.length>=10&&t.length<=80).length,clamp=n=>Math.max(45,Math.min(96,Math.round(n))),natural=clamp(58+Math.min(28,total/18)),question=clamp(52+questions*9),empathyScore=clamp(55+empathy*8),interest=clamp(50+warmth*8),balance=clamp(50+balanced*7),overall=Math.round((natural+question+empathyScore+interest+balance)/5),strengths=[],tips=[];if(question>=72)strengths.push("상대에게 관심을 돌려주는 질문이 충분했어요.");else tips.push("상대 답변의 한 단어를 잡아 짧은 꼬리질문을 해보세요.");if(empathyScore>=72)strengths.push("대답 전에 반응을 넣어 대화가 덜 인터뷰처럼 느껴졌어요.");else tips.push("질문 전에 ‘그랬구나’, ‘재밌겠다’ 같은 반응을 먼저 넣어보세요.");if(interest>=72)strengths.push("호감을 너무 과하지 않게 표현했어요.");else tips.push("후반에는 ‘다음에 같이 해보고 싶다’ 같은 작은 호감 신호를 시도해보세요.");if(!strengths.length)strengths.push("끝까지 대화를 이어간 것 자체가 좋은 연습이었어요.");return{overall,metrics:{natural:{label:"자연스러움",score:natural},question:{label:"질문력",score:question},empathy:{label:"공감",score:empathyScore},interest:{label:"호감 표현",score:interest},balance:{label:"대화 균형",score:balance}},style:question>=75&&empathyScore>=75?"호기심 많은 공감형":interest>=78?"적극적인 호감형":balance>=76?"안정적인 대화형":"신중한 탐색형",summary:overall>=82?"실전에서도 꽤 자연스럽게 이어갈 수 있는 흐름이었어요.":overall>=68?"기본 흐름은 좋아요. 몇 군데만 다듬으면 훨씬 편안해질 수 있어요.":"질문보다 먼저 상대 말에 반응하는 습관을 넣으면 빠르게 좋아질 수 있어요.",strengths,tips,nextChallenge:question<70?"다음 연습에서는 답변마다 꼬리질문 1개씩 만들기":interest<70?"대화 후반에 자연스러운 다음 만남 신호 보내기":"더 까다로운 상대 유형으로 난이도 올리기"};}
export function fallbackPostDateReply({messages,chemistry=60,goal="thanks"}){const last=messages.filter(m=>m.role==="user").at(-1)?.content||"";if(chemistry<35)return"오늘 만나서 반가웠어요. 조심히 들어가세요 :)";if(goal==="second-date"){if(/다음|또|같이|주말|시간/.test(last))return"저도 오늘 재밌었어요 ㅎㅎ 다음에 얘기했던 곳 같이 가요. 다음 주말은 어때요?";return"저도 잘 들어왔어요! 오늘 얘기한 거 재밌었어요 ㅎㅎ";}if(goal==="recover")return"저도 조금 긴장했어요 ㅎㅎ 그래도 편하게 얘기해서 좋았어요. 너무 신경 쓰지 마세요!";return chemistry>=70?"저도 오늘 즐거웠어요 :) 조심히 들어가고 다음에 또 봐요!":"네 저도 반가웠어요! 조심히 들어가세요 :)";}
